name: Ratazzi's Blog
description: Nothing
meta_description: "Life, Works and more"
permalink: /:categories/:year/:month/:day/:title

markdown: rdiscount
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://ratazzi.org'
google_analytics: 'UA-9840465-1'

# Details for the RSS feed generator
url:            'http://ratazzo.org'
author:         'Ratazzi'
